#!/bin/sh
diffs=$(node_modules/.bin/prettier --list-different "{src,tests}/**/*.{ts,tsx,js,jsx}")

[ -z "$diffs" ] && exit 0

echo >&2 "Javascript files must be formatted with prettier. Please run:\n"
echo >&2 " npm run prettier \n"
echo >&2 "These files need to be formatted:\n"
echo >&2 "$diffs"
echo >&2 "\n"

exit 1
